mAAdhaTTah/brookjs

- README.md
- combineActionReducers/README.md
- combineActionReducers/__tests__/combineActionReducers.spec.js
- combineActionReducers/index.js
- index.js
Provides a function for replacing long switch statements with a simplified
mapping of action types to reducer function, combining those tuples to
form an easy to understand reducer function.
> Add combineActionReducers

- .babelrc
- README.md
- package.json
- src/children/index.js
- src/children/mutations.js
`flatten` doesn't need it to be an array, and we can repace `forEach` w/
`R.forEach` so we don't need to use `Array.from`.
Fixes #11.
> Remove Array.from

- src/children/child.js
Because Object.assign calls the getter as part of the assignment, instead of
copying the getter, the console.warn is called immediately, rather than at
the point the userland code accesses it.
> Fix deprecation warning on action.key

- src/children/mutations.js
The nodes are attached to the payload, not the action itself, so this
ensures we grab it from the right place.
> Fix indexOf check for new nodes

- src/observeDelta/index.js
The store doesn't handle errors, and errors emitted from the delta
into the store just... disappear. This should improve the developer
experience, as errors emitted from, say, an ajax request that isn't
handled in the delta would produce no discernible side effect.
> Log all errors emitted into the delta

- src/observeDelta/__tests__/observeDelta.spec.js
- src/observeDelta/index.js
We borrowed this from `redux-observable`, which shares the MIT
license.
> Add ofType to actions$ stream

- src/render/index.js
We don't need to keep re-enabling it. Just enable it at the start and
disable during cleanup.
> Simplify raf$ stream

- docs/source/component.md
- src/component/index.js
- src/constants/index.js
The Symbol allows us to hold onto some metadata about the
component. We'll start by breaking apart the component
generation into a sink & source stream. We're going to update the
`children` stream to only handle children as sources, allowing the
main component to be mounted and handle the entire rendering
context rather than switching rendering contexts between BE & FE.
Add to release notes:
```markdown
* **BREAKING**: Remove `render$` from combinator in `component`. This is a result of a change in the internals, which we're sets up an incoming change in the rendering context.
```
> Extract internals object and attach to factory

- docs/source/children.md
- docs/source/component.md
- docs/source/managing-children-components-in-a-component.md
- docs/source/using-a-template-to-render-a-component.md
- src/children/__tests__/children.spec.js
- src/children/__tests__/util.js
- src/children/child.js
- src/children/index.js
- src/constants/index.js
- src/helpers/blackboxAttribute.js
- src/helpers/index.js
- src/render/__tests__/render.spec.js
- src/render/index.js
We're not longer going to stream values into subsections of the DOM,
so much as just render the HTML for the whole page and update the
entire DOM as appropriate. The top-level component sets the context
for the HTML, so props get passed through the partial context rather
than having to do it in both the the partial context in the BE & the
stream context in the FE.
Add this to the release notes:
```markdown
* **BREAKING**: Rendering now happens from the root component down, rather than streaming individual values into individual components. This allows Handlebars to be the only context through which the developer has to understand the data flow into the DOM.
* **BREAKING**: Blackboxing is now handled explicitly through the use of `dat-brk-blackbox`. This can be used to carve out sections …
```
> Modify rendering context to be top-down

- .babelrc
- .eslintrc.js
- docs/source/helpers.md
- package.json
- src/helpers/__tests__/helpers.spec.js
- src/helpers/mapActionTo.js
Move the `source` information to `meta`.
Fixes #30.
> Make mapActionTo Comply w/ Flux Standard Action

- src/domDelta/__tests__/domDelta.spec.js
- src/domDelta/index.js
Sorry to be annoying, but in reviewing the documentation, I felt this was
a more appropriate parameter name for this function.
> Deprecate `component` in favor of `view`

- docs/source/building-the-reducer-with-combineActionReducers.md
There was a mismatch between the declared reducers and the ones being used.
> Fix typos in code example

- docs/source/animating-a-component.md
There was a typo in the GFM for a code block for Handlebars.
> Fix typo in code example markdown

- .travis.yml
Keeps the yarn.lock file up to date. Sticking with yarn for now
because I have unrelated issues with to sort out with npm@5, so I'm
still on npm@4.
Fixes #62.
> Add greenkeeper-lockfile

- src/children/__tests__/util.spec.js
- src/children/mutations.js
- src/children/util.js
This fixes an odd bug I'm having in my app since switching to
diffhtml: sometimes, the MutationObserver emits 3 records for a
single node, an add, a remove, and an add. The current algorithm
was deduping too aggressively, eliminating all 3 of the records for
the node, depending on the order in which they arrived. This
resolves that issue by chunking up the list and cancelling out
matching cross-types, so we're only left with the single
appropriate action.
This may be some of the worst code I've ever written, but this is
a show-stopper, as the children aren't mounting nodes that are
added to the DOM and thus being rendered inert. I fully intend
to refactor this once I'm both able to reproduce a usable test
case for the utility function as well as reproduce it against an
actual …
> Fix bug when MObs emits 3 actions for node

- src/render/patchAsObservable.js
An incoming PR to diffhtml makes this change as well.
`createNode` checks the NodeCache first to see if the node
exists there, then goes ahead and creates it if it doesn't find
it.
> Use `createNode` instead of `NodeCache`

- src/render/__tests__/fixtures/index.js
- src/render/__tests__/fixtures/rootBlackboxed.hbs
- src/render/__tests__/render.spec.js
- src/render/middleware.js
A component at the root of the render tree is in control of its entire
tree, so we expect the component to be using `renderFromHTML` and
updating it as part of a custom render cycle. A component won't
blackbox itself _from itself_, but will want to blackbox itself from its
parent components. This ensures it can render itself as it chooses.
Comes with tests!
> Enable root blackboxed components to be rendered

- src/children/__tests__/children.spec.js
- src/children/util.js
`groupWith` didn't work like I expected, only grouping adjacent
nodes. Using `groupBy` just groups them into keys. Because
there's only 2 possible keys, we can `R.values` and end up
with what we wanted.
> Cleanup action dedupe algorithm

- src/index.js
No reason to export in both places here. No one is going to
`const brookjs = requrire('brookjs').default` when you can
`require('brookjs')` to get the same thing.
> Remove default export from package

- README.md
- packages/brookjs-silt/src/__tests__/h.spec.js
- packages/brookjs-silt/src/h.js
Use `filterProps` in both paths for consistency.
> Fix props migration on alternate code path

- flow-typed/npm/chai_v4.x.x.js
- packages/brookjs-silt/src/__tests__/loop.spec.js
- packages/brookjs-silt/src/loop.js
This is often combined, so easier to just enable it in the `loop`.
Fixes #137.
> Allow passing `mapper` in first

- packages/brookjs-cli/src/selectors/build.js
This allows the developer to e.g. modify the extensions depending on
whether or not it's in development or production.
> Allow filenames to be dynamic

- packages/brookjs-silt/src/fromReact.js
- packages/brookjs-silt/src/index.js
This allows you to use your React components into your old-style
brookjs components, migrating your leaf components to React in
a piecemeal fashion without needing to overhaul the entire app at once.
Like the old-style component, you'll need to continue to use
`data-brk-container` to point at the node where React should be mounted.
Additionally, you'll need to use `data-brk-blackbox` so brookjs doesn't
modify the node that React now controls. See this PR for an example:
https://github.com/intraxia/wp-gistpen/pull/237
Fixes #153.
> Add fromReact wrapper helper

- packages/brookjs-silt/package.json
- packages/brookjs-silt/src/__tests__/Aggregator.spec.js
- packages/brookjs-silt/src/__tests__/Collector.spec.js
- packages/brookjs-silt/src/__tests__/withRef$.spec.js
- packages/brookjs-silt/src/withRef$.js
- yarn.lock
This enables us to drop the required React version again and reenable
the other tests.
Fixes #182.
> Use create-react-ref in withRef$ HOC

- packages/brookjs/src/component/children/index.js
- packages/brookjs/src/component/events/index.js
- packages/brookjs/src/component/index.js
- packages/brookjs/src/component/render/index.js
Note that `raf$` and `RAF` are _not_ deprecated.
Fixes #148.
> Deprecate brookjs#component and children

- packages/brookjs-desalinate/package.json
- packages/brookjs-silt/package.json
- packages/brookjs/package.json
- rollup.config.js
This allows us to configure the output file in each package while
sharing a single configuration.
Fixes #262.
> Replace "browser" -> "rollup:dist"

- packages/brookjs/src/__tests__/ofType.spec.js
- packages/brookjs/src/ofType.js
This enables usage with redux-actions, as those functions are castable
to strings.
Fixes #270.
> Add loose equality check to ofType

- packages/brookjs/src/__tests__/eddy.spec.js
- packages/brookjs/src/eddy.js
- packages/brookjs/src/index.js
100% coverage of the eddy module! Add returning `loop.NONE` from one of the
arrays, to ensure we get coverage of the `!== NONE` branch. Also fixed a bug
in the `runCommands`, which was calling the original `store.dispatch` instead
of the wrapped `dispatch` function. This would terminate the continuous dispatch
of the returned actions.
> Add combineReducers and clean up tests

- packages/brookjs-cli/package.json
- packages/brookjs-cli/src/selectors/build.js
- yarn.lock
Use webpack-plugin-install-deps instead, which works with webpack 4.
We can switch back if the old one gets updated.
Fixes #234.
> Replace npm-install-webpack-plugin

- packages/brookjs-silt/src/__tests__/withRef.spec.tsx
- packages/brookjs-silt/src/index.ts
- packages/brookjs-silt/src/withRef.tsx
This can be used by consumers to make defining the Refback
function easier.
> Extract and export Refback type

- packages/brookjs-desalinate/package.json
- packages/brookjs-desalinate/src/chaiPlugin.tsx
Forgot to add the last assertion to chai.
> Add missing types to brookjs-desalinate

- packages/brookjs-cli/src/commands/BuildCommand/selectors.ts
This is loose and should eventually be handled via configuration.
> Add typescript support to build

- packages/brookjs-silt/src/withRef.tsx
This is more accurate of what it is, and means you can rely on
certain semantic properties of the... Property.
> Switch `props$` to Kefir.Property

- packages/brookjs-cli/src/commands/NewCommand/View.tsx
- packages/brookjs-cli/src/commands/NewCommand/index.tsx
- packages/brookjs-silt/src/toJunction.tsx
This should make it easier to define `toJunction` wrapped
Components without needing to type it manually.
Fix #374.
> Fix toJunction typings

- packages/brookjs-silt/src/withRef.tsx
If we provide a new callback every time, then React notifies the
callback of the latest ref every time as well. Reusing the callback
ensures it doesn't see it as a new callback to notify.
> Prevent refback from being called repeatedly

- packages/brookjs-cli/features/build.feature
- packages/brookjs-cli/features/support/steps.ts
- packages/brookjs-cli/features/support/world.ts
- packages/brookjs-cli/src/commands/BuildCommand/View.tsx
This makes sure the process exits with `1` if the build fails, which
should fix issues running this in CI with passing builds.
Fixes #381.
> Fix exit code when build fails and not watching

- packages/brookjs-cli/features/build.feature
- packages/brookjs-cli/features/support/steps.ts
These fail constantly and instead of doing anything to reduce the
size, I just keep changing the size limits, so let's just get rid
of this check completely.
> Remove size checks from tests

- packages/brookjs-silt/src/__tests__/useDeltas.spec.ts
- packages/brookjs-silt/src/useDeltas.ts
We'll use `#scan` to manage the reducer part of the flow and
then just pass that state over to `setState` for React to deal
with after.
Fixes #801.
Fixes #836.
> Refactor to use stream at center over useReducer

- packages/brookjs-cli/src/commands/BuildCommand/index.tsx
- packages/brookjs-cli/src/commands/NewCommand/index.tsx
- packages/brookjs-cli/src/commands/TestCommand/Check/index.tsx
- packages/brookjs-cli/src/commands/TestCommand/Lint/index.tsx
- packages/brookjs-cli/src/commands/TestCommand/Unit/index.tsx
- packages/brookjs-silt/src/__tests__/useDelta.spec.ts
- packages/brookjs-silt/src/index.ts
- packages/brookjs-silt/src/useDelta.ts
Accept a single delta, so it matches the API for `createStore`.
Both of these accept a single delta. We should intead encourage
a root delta that combines them all together, providing a point
where the application state & actions can be decoupled from
an individual delta's. We could eventually provide a helper for
this process but start with suggesting manual combinations.
> Update `useDeltas` -> `useDelta`

- packages/brookjs-cli/src/cli/App.tsx
If we keep it in this context, there's no cross-realm problems,
which webpack's validation chokes on. There add an `instanceof`
keyword to ajv, which they use to validate the regex & functions
passed in. Running in another context creates a new set of globals,
so those `instanceof` check fail.
> Run function in current context

- packages/brookjs-silt/src/context.ts
- packages/brookjs-silt/src/toJunction.tsx
- packages/brookjs-silt/src/useDelta.ts
- packages/brookjs-silt/src/withRef.tsx
This is what we call it in the documentation so it makes more sense
to call it that within the application as well.
> Plug useDelta into (renamed) CentralObservable

- packages/brookjs-cli/src/commands/TestCommand/Unit/exec.ts
These aren't tested separately so we don't need coverage for them.
Fixes #1075.
> Exclude .stories.js & __stories__ from coverage

- package.json
- yarn.lock
We're not using this directly anywhere so get rid of it.
> Remove @babel/preset-env as devDep

- packages/brookjs-silt/src/hooks.ts
- packages/brookjs-silt/src/useDelta.ts
We should plug in the `action$` stream, not the `delta$` stream,
because that one has the full set of actions emitted.
Also extract the hooks for reuse later.
> Fix useDelta plugging into the Central Observable

- packages/brookjs-silt/src/RootJunction.tsx
- packages/brookjs-silt/src/__tests__/RootJunction.spec.tsx
- packages/brookjs-silt/src/__tests__/toJunction.spec.tsx
- packages/brookjs-silt/src/__tests__/withRef.spec.tsx
- packages/brookjs-silt/src/context.ts
- packages/brookjs-silt/src/index.ts
- packages/brookjs-silt/src/toJunction.tsx
- packages/brookjs-silt/src/withRef.tsx
We don't actually want to allow errors to be emitted from these.
We should throw/show an error if we get errors because they're
not really handled by anyone anywhere.
> Make Central Observable error channel `never`

- packages/brookjs-silt/src/toJunction.tsx
This prop is only used by the wrapper component and shouldn't
be passed along to the wrapped component.
> Stop forwarding preplug

- packages/brookjs-desalinate/src/jestPlugin.tsx
This ensures it doesn't need to be wrapped in the implementation
when timers interact with the elements.
Fixes #1135.
> Wrap `tick` in `act` on `emitFromJunction`

- packages/brookjs-cli/src/commands/NewCommand/__tests__/View.spec.tsx
- packages/brookjs-silt/src/__tests__/toJunction.spec.tsx
- packages/brookjs-silt/src/context.ts
- packages/brookjs-silt/src/toJunction.tsx
This is a breaking change, as `toJunction`'s `combine` function
now only accepts the resulting combined stream. This makes
it so we don't need to unplug & replug this stream on every
props change. We instead will just need the parent component
to ensure reusing the same function for `preplug`.
> Simplify toJunction implementation

- packages/brookjs-silt/src/__tests__/useDelta.spec.ts
- packages/brookjs-silt/src/useDelta.ts
Plugging events from `dispatch` & `root$` causes duplicate events
to be pushed into the Central Observable. This ensures only events
created within `useDelta` (from the eddy reducer & the delta) are
pushed.
> Plug events created by useDelta

- packages/brookjs-desalinate/src/jestPlugin.tsx
This allows components to update during tests without
needed to wrap the element in RootJunction, similar to
how we do it in the initial render.
> Wrap rerender in RootJunction
