mAAdhaTTah/brookjs

docs/source/_data/nav.yml
docs/source/combineActionReducers.md
src/combineActionReducers/__tests__/combineActionReducers.spec.js
src/combineActionReducers/index.js

Support default state with combineActionReducers #13

---

src/index.js

Export `render` & `children` from entry

---

src/render/index.js

Simplify the logic indicating which element(s) should be updated.
Copious code comments were added.

Clean up rendering logic

---

docs/source/children.md
src/children/__tests__/children.spec.js
src/children/__tests__/util.js
src/children/child.js
src/children/index.js
src/children/util.js

Children Module Improvements

---

README.md
docs/package.json
docs/source/_data/nav.yml
docs/source/changelog.md
docs/themes/documentation/helper/index.js
docs/themes/documentation/layout/index.hbs

Add changelog to website

---

src/children/__tests__/children.spec.js
src/children/child.js
src/children/index.js
src/children/mutations.js
src/children/util.js

1 bug, 1 function rename, 1 refactor.

Improve the children module

---

docs/source/_data/nav.yml
docs/source/handling-side-effects-with-observeDelta.md
src/domDelta/__tests__/domDelta.spec.js
src/domDelta/index.js
src/index.js

Add `domDelta` & documentation for mounting the root component to
the DOM.

Add domDelta

---

karma.conf.js
src/component/index.js
src/render/__tests__/render.spec.js
webpack.config.js

Add some additional tests & assertions.

Test Improvements

---

docs/source/events.md
src/events/__tests__/events.spec.js
src/events/event.js
src/events/index.js

Add ProxyEvent

---

src/children/child.js
src/domDelta/index.js
src/helpers/__tests__/helpers.spec.js
src/helpers/mapActionTo.js

The next release will have all the deprecated configurations
removed.

Remove all deprecated code

---

docs/source/component.md
src/children/__tests__/children.spec.js
src/children/__tests__/util.js
src/children/child.js
src/children/index.js
src/component/__tests__/component.spec.js
src/component/index.js

Fixes #58. The title of the issue is a little misleading.

Mount DOM without template

---

src/render/patchAsObservable.js

Ported from [diffhtml][1].
[1]: https://github.com/tbranyen/diffhtml/blob/b948d5cd5e4c090dce5ab48eb25803848c49340d/packages/diffhtml/lib/node/patch.js

Add blacklist to patchAsObservable

---

packages/brookjs-silt/src/__tests__/generate.spec.js
packages/brookjs-silt/src/__tests__/parse.spec.js
packages/brookjs-silt/src/ast/index.js
packages/brookjs-silt/src/generate/index.js
packages/brookjs-silt/src/parse/expression.js

Handlebars comments & parse climbing context. This doesn't
generate the correct vdom yet.

Add additional spec compliance

---

docs/source/implementing-side-effects-with-custom-delta.md
package-lock.json
package.json
src/index.js
src/kefir.js
src/observeDelta/__tests__/observeDelta.spec.js
src/observeDelta/index.js

Bump minimum version requirement for kefir. Update docs.
Fixes #91.

Eliminate Kefir extension in favor of Kefir#thru

---

packages/brookjs-silt/src/Collector.js

Also correctly works for stateless functional components.
I don't see this as necessarily the final approach, but it
gets things working and fixes an issue whereby React
was seeing these wrapped components as "new" and
therefore pruning and rerendering that chunk of the DOM.

Add caching for wrapped components

---

packages/brookjs-silt/src/Collector.js
packages/brookjs-silt/src/__tests__/events.spec.js

We don't need to wrap components but can instead just modify
the components in place.
Fixes #131.

Fix bugs in rendering process

---

packages/brookjs/package.json
packages/brookjs/src/fromReduxStore/__tests__/fromReduxStore.spec.js
packages/brookjs/src/fromReduxStore/index.js
yarn.lock

This converts a redux store into a Kefir Property.
Fixes #141.

Add fromReduxStore module

---

packages/brookjs-silt/src/__tests__/h.spec.js
packages/brookjs-silt/src/h.js

This is probably going to result in unexpected behaviors, so
warn developers so they don't mess this up and wonder why
it's not working.
Fixes #140.

Show warning if using stream

---

yarn.lock

Update lockfile to latest versions

---

packages/brookjs-silt/src/__tests__/withRef$.spec.js
packages/brookjs-silt/src/withRef$.js

Fix withRef$ to unplug properly with unmounted

---

packages/brookjs-silt/package.json
packages/brookjs-silt/src/Aggregator.js
packages/brookjs-silt/src/Collector.js
packages/brookjs-silt/src/RootJunction.js
packages/brookjs-silt/src/__tests__/RootJunction.spec.js
packages/brookjs-silt/src/__tests__/h.spec.js
packages/brookjs-silt/src/__tests__/toJunction.spec.js
packages/brookjs-silt/src/index.js
packages/brookjs-silt/src/toJunction.js
packages/brookjs-silt/src/withRef.js
yarn.lock

New collector api

---

packages/brookjs-silt/src/__tests__/observableOf.spec.js
packages/brookjs-silt/src/__tests__/withRef.spec.js
packages/brookjs-silt/src/observableOf.js

observableOf tests

---

packages/babel-preset-brookjs/package.json
packages/brookjs-cli/package.json
packages/brookjs-desalinate/package.json
packages/brookjs-silt/package.json
packages/brookjs/package.json

Add pkg#files and descriptions.
Fixes #231.

Fix package.json

---

packages/babel-preset-brookjs/package.json
packages/brookjs-cli/package.json
packages/brookjs-desalinate/package.json
packages/brookjs-silt/package.json
packages/brookjs/package.json

Add "sideEffects": false to all pkg.json

---

packages/babel-preset-brookjs/index.js
packages/brookjs-cli/features/__snaps__/developer-runs-new-and-accepts-the-defaults.snap
packages/brookjs-cli/features/__snaps__/developer-runs-new-and-answers-the-prompts.snap
packages/brookjs-cli/features/build.feature
packages/brookjs-cli/src/deltas/npmDelta.js
packages/brookjs-cli/templates/project/new/.eslintrc.js.ejs
packages/brookjs-cli/templates/project/new/app.js.ejs
packages/brookjs-silt/src/index.js
packages/hygen-brookjs-generators/_templates/components/new/instance.js.ejs

Fixes #119.
Fixes #209 (setting `h` as default).

Update to use silt in the cli

---

packages/brookjs-cli/features/build.feature
packages/brookjs-desalinate/package.json
packages/brookjs-desalinate/src/__tests__/chaiPlugin.spec.js
packages/brookjs-desalinate/src/chaiPlugin.js
yarn.lock

Add support for testing deltas

---

packages/brookjs-silt/src/__tests__/toJunction.spec.js
packages/brookjs-silt/src/toJunction.js

Update toJunction to accept events directly

---

packages/brookjs-silt/src/__tests__/withRef.spec.js
packages/brookjs-silt/src/withRef.js

This isn't likely to happen often, but should be handled correctly.

Fix withRef updating when aggregated$ changes

---

packages/brookjs-silt/src/__tests__/toJunction.spec.tsx
packages/brookjs-silt/src/index.ts
packages/brookjs-silt/src/toJunction.tsx

This are useful to implementers, so let's make them available.

Export additional types from toJunction module

---

packages/brookjs-cli/package.json
packages/brookjs-desalinate/package.json
packages/brookjs-silt/package.json
packages/brookjs-silt/src/__tests__/useDeltas.spec.ts
packages/brookjs-silt/src/useDeltas.ts
packages/brookjs/src/eddy.ts
yarn.lock

Add support for EddyReducer in useDeltas

---

.eslintrc.js
packages/brookjs-cli/src/commands/BuildCommand/__tests__/View.spec.tsx
packages/brookjs-cli/src/commands/BuildCommand/__tests__/selectors.spec.ts
packages/brookjs-cli/src/commands/NewCommand/__tests__/View.spec.tsx
packages/brookjs-cli/src/commands/NewCommand/__tests__/exec.spec.ts
packages/brookjs-cli/src/commands/TestCommand/__tests__/View.spec.tsx
packages/brookjs-cli/src/setupTests.ts
packages/brookjs-desalinate/extend-expect.d.ts
packages/brookjs-desalinate/extend-expect.js
packages/brookjs-desalinate/package.json
packages/brookjs-desalinate/src/__tests__/jestPlugin.spec.tsx
packages/brookjs-desalinate/src/setupTests.ts
packages/brookjs-flow/src/__tests__/ofType.spec.ts
packages/brookjs-flow/src/__tests__/view.spec.ts
packages/brookjs-flow/src/setupTests.ts
packages/brookjs-silt/src/__tests__/RootJunction.spec.tsx
packages/brookjs-silt/src/__tests__/toJunction.spec.tsx
packages/brookjs-silt/src/__tests__/useDeltas.spec.ts
packages/brookjs-silt/src/__tests__/withRef.spec.tsx
packages/brookjs-silt/src/setupTests.ts
packages/brookjs/src/__tests__/fromReduxStore.spec.ts
packages/brookjs/src/__tests__/observeDelta.spec.ts
packages/brookjs/src/setupTests.ts

Add extend-expect to brookjs-desalinate

---

packages/brookjs-cli/features/support/steps.ts
packages/brookjs-cli/src/commands/NewCommand/View.tsx
packages/brookjs-cli/src/commands/TestCommand/__tests__/View.spec.tsx
packages/brookjs-cli/tsconfig.json
packages/brookjs-desalinate/extend-expect.d.ts
packages/brookjs-desalinate/src/__tests__/jestPlugin.spec.tsx
packages/brookjs-desalinate/stories/Button.tsx
packages/brookjs-desalinate/tsconfig.json
packages/brookjs-flow/src/__tests__/ofType.spec.ts
packages/brookjs-flow/tsconfig.json
packages/brookjs-silt/src/__tests__/toJunction.spec.tsx
packages/brookjs-silt/src/__tests__/useDeltas.spec.ts
packages/brookjs-silt/src/__tests__/withRef.spec.tsx
packages/brookjs-silt/src/toJunction.tsx
packages/brookjs-silt/src/withRef.tsx
packages/brookjs-silt/tsconfig.json
packages/brookjs-types/tsconfig.json
packages/brookjs/src/__tests__/fromReduxStore.spec.ts
packages/brookjs/src/__tests__/observeDelta.spec.ts
packages/brookjs/tsconfig.json

Enable typechecking for the tests

---

packages/brookjs-cli/src/webpack/index.ts

Fix importLoaders value

---

packages/brookjs-cli/features/__snaps__/developer-runs-new-and-accepts-the-defaults.snap
packages/brookjs-cli/features/__snaps__/developer-runs-new-and-answers-the-prompts.snap
packages/brookjs-cli/features/__snaps__/developer-runs-new-with-ts-and-accepts-the-defaults.snap
packages/brookjs-cli/templates/project/new/dir-index.js.ejs
packages/brookjs-cli/templates/project/new/package.json.ejs

We should figure out the polyfilling story, but otherwise, let's not
default to anything right now.

Remove @babel/polyfill

---

packages/brookjs-silt/src/RootJunction.tsx
yarn.lock

Make sure we can tap into the child root from parent RootJunctions.

Plug the child root into the parent root

---

packages/brookjs-desalinate/src/jestPlugin.tsx
packages/brookjs-silt/src/RootJunction.tsx

Fix some bugs as I was putting together the walkthroughs.

Beta bugfixes

---

packages/brookjs-cli/bin/beaver.js
packages/brookjs-cli/src/cli/App.tsx
packages/brookjs-cli/src/cli/__tests__/App.spec.ts
packages/brookjs-cli/src/cli/__tests__/__fixtures__/commands-file.js
packages/brookjs-cli/src/cli/__tests__/__fixtures__/commands-folder-with-relative/ValidCommand.js
packages/brookjs-cli/src/cli/__tests__/__fixtures__/commands-folder-with-relative/index.js
packages/brookjs-cli/src/cli/__tests__/__fixtures__/commands-folder/index.js

Add tests for loading commands from various potential sources.
Fixes #1015.

Fix load resoluition of commands

---

packages/brookjs-cli/src/cli/App.tsx

Ignore helpers and handle internal modules.

Improve loading logic

---

package.json
packages/brookjs-cli/features/__snaps__/developer-runs-new-and-accepts-the-defaults.snap
packages/brookjs-cli/features/__snaps__/developer-runs-new-and-answers-the-prompts.snap
packages/brookjs-cli/features/__snaps__/developer-runs-new-with-ts-and-accepts-the-defaults.snap
packages/brookjs-cli/templates/project/new/package.json.ejs
packages/brookjs-desalinate/package.json
packages/brookjs-docs/examples/commands-deltas-and-side-effects/package.json
packages/brookjs-docs/examples/emitting-component-events-through-observables/package.json
packages/brookjs-docs/examples/making-a-todo-list/package.json
packages/brookjs-docs/examples/testing-format-lint-unit/package.json
yarn.lock

Bump this up to v10 by default.

Bump version of @testing-library/react

---

packages/brookjs-desalinate/extend-expect.d.ts

This is needed for Intellisense to work right.

Fix the names of the values sent into delta

---

packages/brookjs-cli/src/commands/TestCommand/Unit/exec.ts

Merge Jest configuration instead of overwriting

---

packages/brookjs-silt/src/__tests__/withRef.spec.tsx
packages/brookjs-silt/src/withRef.tsx

This is much less code and easier to maintain.

Convert withRef$ to hooks
